### ISSUE TITLE
Does not support auto-save

### ISSUE THREAD

**Issue by Gaming32** [zh28/file-size#4]
When I save the file with Ctrl+S, the file size on the status bar updates. However, when the file auto-saves because I click away, the file size indicator remains unchanged.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/42721887/96904476-ccc5e480-145c-11eb-858c-9be4f213cb7d.gif)

**Comment by zhcode66** [comment]
Thanks for the feedback!
I'll release a version to fix it.

**Comment by zhcode66** [comment]
> Thanks for the feedback!
> I'll release a version to fix it.

Published.
